//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agentslist
    {
        public int slno { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<byte> isavailable { get; set; }
        public Nullable<byte> islogin { get; set; }
        public Nullable<int> assigncount { get; set; }
    }
}
