//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class callflow
    {
        public int slno { get; set; }
        public string @event { get; set; }
        public string caller { get; set; }
        public string callee { get; set; }
        public string from_number { get; set; }
        public string to_number { get; set; }
        public string callstatus { get; set; }
        public string endreason { get; set; }
        public Nullable<int> report_id { get; set; }
        public string calluid { get; set; }
        public Nullable<System.DateTime> insertedtimestamp { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string dialstatus { get; set; }
    }
}
