//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clicktocall_reports
    {
        public int slno { get; set; }
        public string ClientNumber { get; set; }
        public string IvrNumber { get; set; }
        public string Status { get; set; }
        public string calluid { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string EndReason { get; set; }
        public Nullable<System.DateTime> insertedtimestamp { get; set; }
        public string ClientIp { get; set; }
        public Nullable<byte> IsUpdatedByJob { get; set; }
        public string ClientName { get; set; }
        public string ClientEmail { get; set; }
    }
}
