//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference_members
    {
        public int id { get; set; }
        public Nullable<int> conf_id { get; set; }
        public string member_name { get; set; }
        public string mobile_number { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string District { get; set; }
        public string Mandal { get; set; }
        public string member_type { get; set; }
        public string email { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<byte> Is_DND { get; set; }
        public Nullable<byte> OptedInstructionsSent { get; set; }
        public Nullable<byte> IsOptedIn { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<decimal> ContactId { get; set; }
        public string Token { get; set; }
        public Nullable<byte> IsParticipate { get; set; }
        public Nullable<byte> CountryID { get; set; }
        public string Prefix { get; set; }
    }
}
