//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceRunTrack
    {
        public decimal Slno { get; set; }
        public Nullable<decimal> ConferenceId { get; set; }
        public string BatchId { get; set; }
        public string Moderator { get; set; }
        public Nullable<int> TotalMembers { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    }
}
