//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference_members_devicetoken
    {
        public int id { get; set; }
        public Nullable<int> conf_id { get; set; }
        public string mobilenumber { get; set; }
        public Nullable<byte> appsource { get; set; }
        public string androiddevicetoken { get; set; }
        public string iosdevicetoken { get; set; }
    }
}
