//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference_studio
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string conf_room { get; set; }
        public string moderator { get; set; }
        public string member { get; set; }
        public string start_conf_onenter { get; set; }
        public string end_conf_onexit { get; set; }
        public string wait_clip { get; set; }
        public string conf_name { get; set; }
        public Nullable<int> report_id { get; set; }
        public string record_conf { get; set; }
        public string mute_member { get; set; }
        public string welcome_clip { get; set; }
        public string conferencetype { get; set; }
        public string conf_date { get; set; }
        public string from_time { get; set; }
        public string to_time { get; set; }
        public string conf_accesskey { get; set; }
        public string conf_number { get; set; }
        public string mute { get; set; }
        public string excel_upload { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UserCallerIdSlno { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string ReminderSendBefore { get; set; }
        public Nullable<byte> IsAutoDial { get; set; }
        public string generateby { get; set; }
        public string custom_email { get; set; }
        public Nullable<int> TimeZoneMinutes { get; set; }
        public Nullable<int> duration { get; set; }
    }
}
