//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceAutoDialInfo
    {
        public int id { get; set; }
        public Nullable<int> ConfId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Token { get; set; }
        public Nullable<byte> IsStarted { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    }
}
