//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceInterConnectNumber
    {
        public int Slno { get; set; }
        public string CallerIdNumber { get; set; }
        public Nullable<byte> GateWayID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public string FromNumber { get; set; }
    }
}
