//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference_schedules
    {
        public int id { get; set; }
        public Nullable<int> conf_id { get; set; }
        public Nullable<int> sch_type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string sch_day { get; set; }
        public Nullable<int> sch_month { get; set; }
        public string day_on_month { get; set; }
        public Nullable<System.DateTime> inserted_ts { get; set; }
        public Nullable<System.DateTime> updated_ts { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<int> IsAvailable { get; set; }
        public string sch_WeekDays { get; set; }
        public string ReminderSendBefore { get; set; }
        public Nullable<byte> IsAutoDial { get; set; }
        public string AutoDial { get; set; }
        public Nullable<int> TimeZoneMinutes { get; set; }
    }
}
