//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacts_groups
    {
        public int groupid { get; set; }
        public Nullable<int> parentid { get; set; }
        public string groupname { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<System.DateTime> insertedat { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
    }
}
