//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacts_feb_08_2015
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string mobile_number { get; set; }
        public string email_id { get; set; }
        public string user_id { get; set; }
        public Nullable<byte> Is_DND { get; set; }
        public Nullable<byte> OptedInstructionsSent { get; set; }
        public Nullable<byte> IsOptedIn { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
