//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleteConferenceMembersTracking
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<byte> IsDnd { get; set; }
        public Nullable<byte> OptinSent { get; set; }
        public Nullable<byte> IsOptedInt { get; set; }
        public Nullable<int> ConfId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    }
}
