//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class deletecontactid
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<long> contactid { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> inserted_ts { get; set; }
    }
}
