//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_templates
    {
        public int id { get; set; }
        public string Template_name { get; set; }
        public string email_subject { get; set; }
        public string email_body { get; set; }
        public string @params { get; set; }
        public string Procedurename { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string message_body { get; set; }
    }
}
