//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class errors_log
    {
        public string proc_name { get; set; }
        public string err_msg { get; set; }
        public decimal id { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> err_line { get; set; }
    }
}
