//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GateWay
    {
        public byte GateWayId { get; set; }
        public string GateWayName { get; set; }
        public string OriginationURL { get; set; }
        public string HttpURL { get; set; }
        public string ExtraDialString { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
        public Nullable<byte> CountryID { get; set; }
        public string ResourcesUrl { get; set; }
        public string ResourcesPath { get; set; }
        public string DefaultcallerId { get; set; }
        public string CountryPrefix { get; set; }
        public string DialPrefix { get; set; }
        public Nullable<bool> IsCountryPrefixAllowed { get; set; }
    }
}
