//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdminUserInfo
{
    public int AdminId { get; set; }
    public string FullName { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmailAddress { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> LastLogin { get; set; }
    public string ImageUrl { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class Agentslist
{
    public int slno { get; set; }
    public string Name { get; set; }
    public string Number { get; set; }
    public Nullable<byte> isavailable { get; set; }
    public Nullable<byte> islogin { get; set; }
    public Nullable<int> assigncount { get; set; }
}

public partial class BackUpContacts4Aug
{
    public int id { get; set; }
    public string full_name { get; set; }
    public string mobile_number { get; set; }
    public string email_id { get; set; }
    public string user_id { get; set; }
    public Nullable<byte> Is_DND { get; set; }
    public Nullable<byte> OptedInstructionsSent { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public string designation { get; set; }
    public string location { get; set; }
    public string Department { get; set; }
}

public partial class CallerId
{
    public int Slno { get; set; }
    public string CallerIdNumber { get; set; }
    public string DisplayNumber { get; set; }
    public Nullable<bool> IsAvailable { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<byte> GateWayId { get; set; }
}

public partial class CallerIdsCreateUpdateTracking
{
    public int Id { get; set; }
    public string CallerIdNumber { get; set; }
    public Nullable<int> CallerIdSlno { get; set; }
    public Nullable<int> AssignedTo { get; set; }
    public Nullable<int> AssignedBy { get; set; }
    public string AssignedByEmail { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public string Action { get; set; }
}

public partial class callflow
{
    public int slno { get; set; }
    public string @event { get; set; }
    public string caller { get; set; }
    public string callee { get; set; }
    public string from_number { get; set; }
    public string to_number { get; set; }
    public string callstatus { get; set; }
    public string endreason { get; set; }
    public Nullable<int> report_id { get; set; }
    public string calluid { get; set; }
    public Nullable<System.DateTime> insertedtimestamp { get; set; }
    public Nullable<System.DateTime> starttime { get; set; }
    public Nullable<System.DateTime> endtime { get; set; }
    public string dialstatus { get; set; }
}

public partial class clicktocall_reports
{
    public int slno { get; set; }
    public string ClientNumber { get; set; }
    public string IvrNumber { get; set; }
    public string Status { get; set; }
    public string calluid { get; set; }
    public Nullable<System.DateTime> StartTime { get; set; }
    public Nullable<System.DateTime> EndTime { get; set; }
    public string EndReason { get; set; }
    public Nullable<System.DateTime> insertedtimestamp { get; set; }
    public string ClientIp { get; set; }
    public Nullable<byte> IsUpdatedByJob { get; set; }
    public string ClientName { get; set; }
    public string ClientEmail { get; set; }
}

public partial class conference_call_activities
{
    public int id { get; set; }
    public int report_id { get; set; }
    public int conf_id { get; set; }
    public string calluid { get; set; }
    public string mobile_number { get; set; }
    public string action { get; set; }
    public Nullable<System.DateTime> start_time { get; set; }
    public Nullable<System.DateTime> end_time { get; set; }
}

public partial class conference_members
{
    public int id { get; set; }
    public Nullable<int> conf_id { get; set; }
    public string member_name { get; set; }
    public string mobile_number { get; set; }
    public string Designation { get; set; }
    public string Department { get; set; }
    public string District { get; set; }
    public string Mandal { get; set; }
    public string member_type { get; set; }
    public string email { get; set; }
    public Nullable<int> isactive { get; set; }
    public Nullable<byte> Is_DND { get; set; }
    public Nullable<byte> OptedInstructionsSent { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public Nullable<decimal> ContactId { get; set; }
    public string Token { get; set; }
    public Nullable<byte> IsParticipate { get; set; }
    public Nullable<byte> CountryID { get; set; }
    public string Prefix { get; set; }
}

public partial class conference_members_devicetoken
{
    public int id { get; set; }
    public Nullable<int> conf_id { get; set; }
    public string mobilenumber { get; set; }
    public Nullable<byte> appsource { get; set; }
    public string androiddevicetoken { get; set; }
    public string iosdevicetoken { get; set; }
}

public partial class conference_members_feb_08_2015
{
    public int id { get; set; }
    public Nullable<int> conf_id { get; set; }
    public string member_name { get; set; }
    public string mobile_number { get; set; }
    public string Designation { get; set; }
    public string Department { get; set; }
    public string District { get; set; }
    public string Mandal { get; set; }
    public string member_type { get; set; }
    public string email { get; set; }
    public Nullable<int> isactive { get; set; }
    public Nullable<byte> Is_DND { get; set; }
    public Nullable<byte> OptedInstructionsSent { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public Nullable<decimal> ContactId { get; set; }
    public string Token { get; set; }
    public Nullable<byte> IsParticipate { get; set; }
}

public partial class conference_membersBackup
{
    public int id { get; set; }
    public Nullable<int> conf_id { get; set; }
    public string member_name { get; set; }
    public string mobile_number { get; set; }
    public string Designation { get; set; }
    public string Department { get; set; }
    public string District { get; set; }
    public string Mandal { get; set; }
    public string member_type { get; set; }
    public string email { get; set; }
    public Nullable<int> isactive { get; set; }
    public Nullable<byte> Is_DND { get; set; }
    public Nullable<byte> OptedInstructionsSent { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public Nullable<decimal> ContactId { get; set; }
    public string Token { get; set; }
    public Nullable<byte> IsParticipate { get; set; }
}

public partial class conference_schedules
{
    public int id { get; set; }
    public Nullable<int> conf_id { get; set; }
    public Nullable<int> sch_type { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public string sch_day { get; set; }
    public Nullable<int> sch_month { get; set; }
    public string day_on_month { get; set; }
    public Nullable<System.DateTime> inserted_ts { get; set; }
    public Nullable<System.DateTime> updated_ts { get; set; }
    public Nullable<System.TimeSpan> StartTime { get; set; }
    public Nullable<int> IsAvailable { get; set; }
    public string sch_WeekDays { get; set; }
    public string ReminderSendBefore { get; set; }
    public Nullable<byte> IsAutoDial { get; set; }
    public string AutoDial { get; set; }
    public Nullable<int> TimeZoneMinutes { get; set; }
}

public partial class conference_schedules_Trakings
{
    public int id { get; set; }
    public Nullable<int> conf_id { get; set; }
    public Nullable<int> sch_type { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public string sch_day { get; set; }
    public Nullable<int> sch_month { get; set; }
    public string day_on_month { get; set; }
    public Nullable<System.DateTime> inserted_ts { get; set; }
    public Nullable<System.DateTime> updated_ts { get; set; }
    public Nullable<System.TimeSpan> StartTime { get; set; }
    public Nullable<int> IsAvailable { get; set; }
    public string sch_WeekDays { get; set; }
    public string ReminderSendBefore { get; set; }
    public Nullable<byte> IsAutoDial { get; set; }
    public string AutoDial { get; set; }
}

public partial class conference_studio
{
    public int id { get; set; }
    public string user_id { get; set; }
    public string conf_room { get; set; }
    public string moderator { get; set; }
    public string member { get; set; }
    public string start_conf_onenter { get; set; }
    public string end_conf_onexit { get; set; }
    public string wait_clip { get; set; }
    public string conf_name { get; set; }
    public Nullable<int> report_id { get; set; }
    public string record_conf { get; set; }
    public string mute_member { get; set; }
    public string welcome_clip { get; set; }
    public string conferencetype { get; set; }
    public string conf_date { get; set; }
    public string from_time { get; set; }
    public string to_time { get; set; }
    public string conf_accesskey { get; set; }
    public string conf_number { get; set; }
    public string mute { get; set; }
    public string excel_upload { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> UserCallerIdSlno { get; set; }
    public Nullable<System.DateTime> Updated_At { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public string ReminderSendBefore { get; set; }
    public Nullable<byte> IsAutoDial { get; set; }
    public string generateby { get; set; }
    public string custom_email { get; set; }
    public Nullable<int> TimeZoneMinutes { get; set; }
    public Nullable<int> duration { get; set; }
}

public partial class ConferenceAutoDialInfo
{
    public int id { get; set; }
    public Nullable<int> ConfId { get; set; }
    public Nullable<int> UserId { get; set; }
    public string Token { get; set; }
    public Nullable<byte> IsStarted { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class ConferenceBalanceDeductionTrack
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserID { get; set; }
    public Nullable<decimal> ConferenceId { get; set; }
    public Nullable<decimal> ReportId { get; set; }
    public string BatchId { get; set; }
    public Nullable<bool> IsInbound { get; set; }
    public Nullable<byte> PulseId { get; set; }
    public Nullable<int> TotalSeconds { get; set; }
    public Nullable<int> TotalPulses { get; set; }
    public Nullable<int> FreeMinutesLeftBeforeDeduction { get; set; }
    public Nullable<int> FreeMinutesDeducted { get; set; }
    public Nullable<double> BalanceLeftBeforeDeduction { get; set; }
    public Nullable<double> BalanceDeducted { get; set; }
    public Nullable<System.DateTime> StartTime { get; set; }
    public Nullable<System.DateTime> EndTime { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class ConferenceInterConnectNumber
{
    public int Slno { get; set; }
    public string CallerIdNumber { get; set; }
    public Nullable<byte> GateWayID { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public string FromNumber { get; set; }
}

public partial class ConferenceRecording
{
    public decimal Slno { get; set; }
    public Nullable<decimal> ConferenceId { get; set; }
    public string CallUUID { get; set; }
    public string FilePath { get; set; }
    public Nullable<System.DateTime> StartTime { get; set; }
    public Nullable<System.DateTime> EndTime { get; set; }
    public Nullable<bool> IsRecording { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public string ResourceUrl { get; set; }
}

public partial class ConferenceRunTrack
{
    public decimal Slno { get; set; }
    public Nullable<decimal> ConferenceId { get; set; }
    public string BatchId { get; set; }
    public string Moderator { get; set; }
    public Nullable<int> TotalMembers { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class contact
{
    public int id { get; set; }
    public string full_name { get; set; }
    public string mobile_number { get; set; }
    public string email_id { get; set; }
    public string user_id { get; set; }
    public Nullable<byte> Is_DND { get; set; }
    public Nullable<byte> OptedInstructionsSent { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public string designation { get; set; }
    public string location { get; set; }
    public string Department { get; set; }
    public Nullable<System.DateTime> insertedtime { get; set; }
    public Nullable<byte> CountryID { get; set; }
    public string Prefix { get; set; }
}

public partial class contacts_feb_08_2015
{
    public int id { get; set; }
    public string full_name { get; set; }
    public string mobile_number { get; set; }
    public string email_id { get; set; }
    public string user_id { get; set; }
    public Nullable<byte> Is_DND { get; set; }
    public Nullable<byte> OptedInstructionsSent { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
}

public partial class contacts_groups
{
    public int groupid { get; set; }
    public Nullable<int> parentid { get; set; }
    public string groupname { get; set; }
    public Nullable<int> userid { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<int> level { get; set; }
    public Nullable<System.DateTime> insertedat { get; set; }
    public Nullable<System.DateTime> updatedat { get; set; }
}

public partial class ContactsBackup
{
    public int id { get; set; }
    public string full_name { get; set; }
    public string mobile_number { get; set; }
    public string email_id { get; set; }
    public string user_id { get; set; }
    public Nullable<byte> Is_DND { get; set; }
    public Nullable<byte> OptedInstructionsSent { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public string designation { get; set; }
    public string location { get; set; }
    public string Department { get; set; }
}

public partial class CountryMaster
{
    public int CountryID { get; set; }
    public string CountryName { get; set; }
    public string CountryCode { get; set; }
    public Nullable<byte> MinLength { get; set; }
    public Nullable<byte> MaxLength { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
}

public partial class CurrencyMaster
{
    public byte CurrencyID { get; set; }
    public string CurrencyName { get; set; }
    public Nullable<double> ConversionRate { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public string CurrencyFullName { get; set; }
}

public partial class DeleteConferenceMembersTracking
{
    public int id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Mobile { get; set; }
    public Nullable<byte> IsDnd { get; set; }
    public Nullable<byte> OptinSent { get; set; }
    public Nullable<byte> IsOptedInt { get; set; }
    public Nullable<int> ConfId { get; set; }
    public Nullable<int> ContactId { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
}

public partial class deletecontactid
{
    public int id { get; set; }
    public Nullable<int> userid { get; set; }
    public Nullable<long> contactid { get; set; }
    public string mobile { get; set; }
    public Nullable<System.DateTime> inserted_ts { get; set; }
}

public partial class DeleteContactsTracking
{
    public int id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Mobile { get; set; }
    public Nullable<byte> IsDnd { get; set; }
    public Nullable<byte> OptinSent { get; set; }
    public Nullable<int> UserId { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<int> ContactId { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class Email_Queue_Conference
{
    public int Email_ID { get; set; }
    public string From_display { get; set; }
    public string From_Addr { get; set; }
    public string To_Addr { get; set; }
    public string CC_Addr { get; set; }
    public string BCC_Addr { get; set; }
    public string Subject { get; set; }
    public string Body { get; set; }
    public byte Mail_Sent { get; set; }
    public Nullable<byte> priority { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string Discription { get; set; }
    public string reply_to { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<long> entryNo { get; set; }
    public Nullable<long> User_Email_Job_No { get; set; }
    public Nullable<int> lang_type { get; set; }
    public string Attachments { get; set; }
    public Nullable<int> Category { get; set; }
}

public partial class email_templates
{
    public int id { get; set; }
    public string Template_name { get; set; }
    public string email_subject { get; set; }
    public string email_body { get; set; }
    public string @params { get; set; }
    public string Procedurename { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public string message_body { get; set; }
}

public partial class EmailCampainResponse
{
    public int id { get; set; }
    public string name { get; set; }
    public string mobile { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public string Token { get; set; }
}

public partial class error_log
{
    public int sno { get; set; }
    public string proc_name { get; set; }
    public string errors { get; set; }
    public Nullable<System.DateTime> time_stamp { get; set; }
    public Nullable<int> err_line { get; set; }
}

public partial class errors_log
{
    public string proc_name { get; set; }
    public string err_msg { get; set; }
    public decimal id { get; set; }
    public System.DateTime time { get; set; }
    public Nullable<int> err_line { get; set; }
}

public partial class FeatureMaster
{
    public byte FeatureId { get; set; }
    public string Description { get; set; }
    public Nullable<byte> DefaultPulseId { get; set; }
    public Nullable<int> DefaultFreeMinutes { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class GateWay
{
    public byte GateWayId { get; set; }
    public string GateWayName { get; set; }
    public string OriginationURL { get; set; }
    public string HttpURL { get; set; }
    public string ExtraDialString { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<byte> CountryID { get; set; }
    public string ResourcesUrl { get; set; }
    public string ResourcesPath { get; set; }
    public string DefaultcallerId { get; set; }
    public string CountryPrefix { get; set; }
    public string DialPrefix { get; set; }
    public Nullable<bool> IsCountryPrefixAllowed { get; set; }
}

public partial class LowBalanceAlertsSent
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
}

public partial class OptedInsSet
{
    public int id { get; set; }
    public string mobile { get; set; }
    public Nullable<byte> IsOptedIn { get; set; }
    public Nullable<System.DateTime> Created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public Nullable<int> UserId { get; set; }
}

public partial class Optin
{
    public int Slno { get; set; }
    public string UserNumber { get; set; }
    public string OptinNumber { get; set; }
    public string OptOutNumber { get; set; }
    public Nullable<bool> IsOptedIn { get; set; }
    public Nullable<System.DateTime> OptedInTimeStamp { get; set; }
    public Nullable<System.DateTime> OptedOutTimeStamp { get; set; }
}

public partial class PulseMaster
{
    public int PulseID { get; set; }
    public Nullable<byte> Pulse { get; set; }
    public Nullable<double> PricePerPulse { get; set; }
    public Nullable<byte> CurrencyID { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class report
{
    public int id { get; set; }
    public string user_id { get; set; }
    public string from_number { get; set; }
    public string to_number { get; set; }
    public Nullable<int> conf_id { get; set; }
    public string member_id { get; set; }
    public string conf_room { get; set; }
    public string member_type { get; set; }
    public string member { get; set; }
    public string requestuuid { get; set; }
    public string calluuid { get; set; }
    public string conf_type { get; set; }
    public string recorded_file { get; set; }
    public string conf_uuid { get; set; }
    public string call_status { get; set; }
    public string record_status { get; set; }
    public Nullable<bool> mute { get; set; }
    public Nullable<bool> deaf { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public Nullable<int> digits_press { get; set; }
    public Nullable<System.DateTime> start_time { get; set; }
    public Nullable<System.DateTime> end_time { get; set; }
    public string end_reason { get; set; }
    public string plivoip { get; set; }
    public string Designation { get; set; }
    public string Department { get; set; }
    public string District { get; set; }
    public string Mandal { get; set; }
    public string BatchId { get; set; }
    public Nullable<System.DateTime> MemberJoinTime { get; set; }
    public Nullable<System.DateTime> MemberExitTime { get; set; }
    public Nullable<bool> IsInbound { get; set; }
    public Nullable<byte> IsRetry { get; set; }
    public Nullable<byte> IsAutodial { get; set; }
    public Nullable<int> SubScriptionType { get; set; }
    public Nullable<double> AmountUsed { get; set; }
    public Nullable<int> TimeZoneMins { get; set; }
    public string PlivoCallUUID { get; set; }
    public Nullable<int> gatewayid { get; set; }
    public Nullable<int> PulseID { get; set; }
    public Nullable<byte> IsInterConnect { get; set; }
    public Nullable<int> ReceivingGatewayId { get; set; }
    public string NodeIp { get; set; }
}

public partial class ScheduleMailTrack
{
    public int id { get; set; }
    public Nullable<int> ConfId { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
}

public partial class Services_HeartBeat_Info
{
    public int ServiceId { get; set; }
    public string Service_Name { get; set; }
    public string Source { get; set; }
    public Nullable<System.DateTime> Last_Beat { get; set; }
    public Nullable<int> Queue_Count { get; set; }
    public string Err_Trace { get; set; }
    public long Err_Count { get; set; }
}

public partial class Services_HeartBeat_Info_Conf
{
    public int ServiceId { get; set; }
    public string Service_Name { get; set; }
    public string Source { get; set; }
    public Nullable<System.DateTime> Last_Beat { get; set; }
    public Nullable<int> Queue_Count { get; set; }
    public string Err_Trace { get; set; }
    public long Err_Count { get; set; }
}

public partial class SMS_Details_Conf
{
    public int slno { get; set; }
    public Nullable<int> contact_id { get; set; }
    public string Mobile_Number { get; set; }
    public string Message { get; set; }
    public string Sender_Id { get; set; }
    public string Message_Type { get; set; }
    public Nullable<System.DateTime> Inserted_Date { get; set; }
    public Nullable<int> Category { get; set; }
}

public partial class SMS_Queue
{
    public int slno { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> User_Job_No { get; set; }
    public string Mobile_Number { get; set; }
    public string Message { get; set; }
    public string Sender_Id { get; set; }
    public string Message_Type { get; set; }
    public Nullable<System.DateTime> Job_Done_Time_Stamp { get; set; }
    public string Sms_Response { get; set; }
    public Nullable<int> Sms_Status { get; set; }
    public Nullable<int> Entery_No { get; set; }
    public Nullable<int> Category { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class SMS_Queue_Conf
{
    public int slno { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> User_Job_No { get; set; }
    public string Mobile_Number { get; set; }
    public string Message { get; set; }
    public string Sender_Id { get; set; }
    public string Message_Type { get; set; }
    public Nullable<System.DateTime> Job_Done_Time_Stamp { get; set; }
    public string Sms_Response { get; set; }
    public Nullable<int> Sms_Status { get; set; }
    public Nullable<int> Entery_No { get; set; }
    public Nullable<int> Category { get; set; }
    public Nullable<int> status { get; set; }
}

public partial class SMS_Reports_Conf
{
    public int slno { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> Entery_No { get; set; }
    public Nullable<int> User_Job_No { get; set; }
    public string Mobile_Number { get; set; }
    public string Message { get; set; }
    public string Sender_Id { get; set; }
    public string Message_Type { get; set; }
    public Nullable<System.DateTime> Job_Done_Time_Stamp { get; set; }
    public Nullable<System.DateTime> Job_Receive_Time_Stamp { get; set; }
    public string Sms_Response { get; set; }
    public string Deliver_Status { get; set; }
    public Nullable<int> Sms_Status { get; set; }
    public Nullable<int> Category { get; set; }
    public Nullable<double> SMS_PPS { get; set; }
}

public partial class SMTP_Queue
{
    public int Email_ID { get; set; }
    public string From_display { get; set; }
    public string From_Addr { get; set; }
    public string To_Addr { get; set; }
    public string CC_Addr { get; set; }
    public string BCC_Addr { get; set; }
    public string Subject { get; set; }
    public string Body { get; set; }
    public byte Mail_Sent { get; set; }
    public Nullable<byte> priority { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string Discription { get; set; }
    public string reply_to { get; set; }
    public Nullable<int> university_id { get; set; }
    public Nullable<long> entryNo { get; set; }
    public Nullable<long> User_Email_Job_No { get; set; }
    public Nullable<int> lang_type { get; set; }
    public string Attachments { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class test_usercallerids
{
    public int Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<int> CallerIdSlno { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> AvailableMinutes { get; set; }
}

public partial class testUserpriceInfo
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<byte> FeatureId { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> PulseId { get; set; }
    public Nullable<int> MaxConcurrency { get; set; }
    public Nullable<int> MinutesLeft { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<int> AdminId { get; set; }
    public Nullable<int> SubscriptionType { get; set; }
}

public partial class TimeZone
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Country { get; set; }
    public Nullable<int> TimeDifferenceInMins { get; set; }
}

public partial class user
{
    public int id { get; set; }
    public string mobile_number { get; set; }
    public string email { get; set; }
    public System.DateTime created_at { get; set; }
    public System.DateTime updated_at { get; set; }
    public string remember_me_token { get; set; }
    public Nullable<System.DateTime> remember_me_token_expires_at { get; set; }
    public Nullable<int> smsc_id { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    public string api_key { get; set; }
    public string access_key { get; set; }
    public string website_url { get; set; }
    public string company { get; set; }
    public string work_number { get; set; }
    public string profile_pic { get; set; }
    public string type { get; set; }
    public Nullable<int> admin_id { get; set; }
    public Nullable<float> balance { get; set; }
    public Nullable<int> pulse_id { get; set; }
    public Nullable<short> is_available { get; set; }
    public string reset_password_token { get; set; }
    public Nullable<System.DateTime> reset_password_token_expires_at { get; set; }
    public Nullable<System.DateTime> reset_password_email_sent_at { get; set; }
    public string soft_phone { get; set; }
    public Nullable<int> is_login { get; set; }
    public string user_password { get; set; }
    public byte[] user_image { get; set; }
    public string mobile_confirm { get; set; }
    public string email_confirm { get; set; }
    public string confirmed_at { get; set; }
    public string USERNAME { get; set; }
    public string email_token { get; set; }
    public Nullable<int> MinimumInboundMinutes { get; set; }
    public Nullable<int> MinimumOutboundMinutes { get; set; }
    public Nullable<byte> DNDAccess { get; set; }
    public Nullable<byte> TRAIAccess { get; set; }
    public string Role { get; set; }
    public Nullable<byte> IsDnd { get; set; }
    public string TimeZone { get; set; }
    public string AcManagerEmail { get; set; }
    public string devicetoken { get; set; }
    public string appsource { get; set; }
    public string deviceuniqueid { get; set; }
    public string androiddevicetoken { get; set; }
    public string countrycode { get; set; }
    public Nullable<int> RegisteredCountryID { get; set; }
}

public partial class user_group_contacts
{
    public int id { get; set; }
    public Nullable<int> contactid { get; set; }
    public Nullable<int> groupid { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<System.DateTime> inserted_ts { get; set; }
    public Nullable<System.DateTime> updated_ts { get; set; }
}

public partial class user_group_contactsBackup
{
    public int id { get; set; }
    public Nullable<int> contactid { get; set; }
    public Nullable<int> groupid { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<System.DateTime> inserted_ts { get; set; }
    public Nullable<System.DateTime> updated_ts { get; set; }
}

public partial class user_groups
{
    public int groupid { get; set; }
    public Nullable<int> userid { get; set; }
    public string groupname { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<System.DateTime> inserted_ts { get; set; }
    public Nullable<System.DateTime> updated_ts { get; set; }
}

public partial class user_login_activities
{
    public int id { get; set; }
    public string user_name { get; set; }
    public string login_ip { get; set; }
    public string login_status { get; set; }
    public Nullable<System.DateTime> login_time { get; set; }
    public Nullable<System.DateTime> logout_time { get; set; }
    public string browser_name { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> source_type { get; set; }
}

public partial class user_login_activities_mod_mem
{
    public int id { get; set; }
    public string user_name { get; set; }
    public string login_ip { get; set; }
    public string login_status { get; set; }
    public Nullable<System.DateTime> login_time { get; set; }
    public Nullable<System.DateTime> logout_time { get; set; }
    public string browser_name { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> source_type { get; set; }
}

public partial class UserBalanceAddingTrack
{
    public int Id { get; set; }
    public Nullable<int> UserId { get; set; }
    public Nullable<int> DialOutMinutes { get; set; }
    public Nullable<int> DialInMInutes { get; set; }
    public Nullable<int> AddedBy { get; set; }
    public string AddedByEmail { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public string Action { get; set; }
}

public partial class UserBalanceDepositHistory
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserBalanceInfoSlno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<double> BalanceBefore { get; set; }
    public Nullable<double> BalanceAfter { get; set; }
    public Nullable<bool> IsActiveBefore { get; set; }
    public Nullable<bool> IsActiveAfter { get; set; }
    public Nullable<System.DateTime> ExpiryDateBefore { get; set; }
    public Nullable<System.DateTime> ExpiryDateAfter { get; set; }
    public Nullable<decimal> AdminId { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> SubscriptionTypePrevious { get; set; }
    public Nullable<int> SubscriptionTypePresent { get; set; }
    public Nullable<long> DialInMinutesPrevious { get; set; }
    public Nullable<long> DialInMinutesPresent { get; set; }
    public Nullable<long> DialOutMinutesPrevious { get; set; }
    public Nullable<long> DialOutMinutesPresent { get; set; }
}

public partial class UserBalanceInfo
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<double> Balance { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<long> DialInMinutes { get; set; }
    public Nullable<long> DialOutMinutes { get; set; }
    public Nullable<int> SubscriptionType { get; set; }
}

public partial class UserBalanceInfo_10Apr
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<double> Balance { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
}

public partial class UserBalanceMaster
{
    public int Slno { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<double> BalanceAmount { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<byte> SubscriptionType { get; set; }
}

public partial class UserCallerId
{
    public int Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<int> CallerIdSlno { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> AvailableMinutes { get; set; }
}

public partial class UserCallerids_10Apr
{
    public int Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<int> CallerIdSlno { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> AvailableMinutes { get; set; }
}

public partial class UserCallerIdsBackUp
{
    public int Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<int> CallerIdSlno { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> AvailableMinutes { get; set; }
}

public partial class UserCallerIDsTriggerTable
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserCallerIdSlno { get; set; }
    public Nullable<decimal> UserID { get; set; }
    public Nullable<int> CallerIdSlno { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<int> AvailableMinutes { get; set; }
    public string TriggerType { get; set; }
    public string TransactionID { get; set; }
}

public partial class UserContactsTraking
{
    public int Slno { get; set; }
    public Nullable<long> UserId { get; set; }
    public Nullable<long> ContactId { get; set; }
    public Nullable<long> GroupId { get; set; }
    public string PreviousContactName { get; set; }
    public string PreviousContactMobile { get; set; }
    public string PreviousContactEmail { get; set; }
    public string PreviousGroupName { get; set; }
    public string CurrentContactName { get; set; }
    public string CurrentContactMobile { get; set; }
    public string CurrentContactEmail { get; set; }
    public string CurrentGroupName { get; set; }
    public string EditedUserMobile { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public string UserChanges { get; set; }
}

public partial class UserMissedCallToGetInformation
{
    public int Id { get; set; }
    public string MobileNumber { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<byte> IsCallBack { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class UserPriceInfo
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<byte> FeatureId { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> PulseId { get; set; }
    public Nullable<int> MaxConcurrency { get; set; }
    public Nullable<int> MinutesLeft { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<int> AdminId { get; set; }
    public Nullable<int> SubscriptionType { get; set; }
}

public partial class UserPriceInfo_10Apr
{
    public decimal Slno { get; set; }
    public Nullable<decimal> UserId { get; set; }
    public Nullable<byte> FeatureId { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    public Nullable<int> PulseId { get; set; }
    public Nullable<int> MaxConcurrency { get; set; }
    public Nullable<int> MinutesLeft { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public Nullable<int> AdminId { get; set; }
    public Nullable<int> SubscriptionType { get; set; }
}

public partial class UserPriceInfoHistory
{
    public decimal Slno { get; set; }
    public Nullable<decimal> PriceInfoSlno { get; set; }
    public Nullable<int> UserId { get; set; }
    public Nullable<byte> FeatureId { get; set; }
    public Nullable<bool> PreviousIsActive { get; set; }
    public Nullable<bool> PresentIsActive { get; set; }
    public Nullable<byte> PreviousPulseId { get; set; }
    public Nullable<byte> PresentPulseId { get; set; }
    public Nullable<int> PreviousConcurrency { get; set; }
    public Nullable<int> PresentConcurrency { get; set; }
    public Nullable<int> PreviousMinutes { get; set; }
    public Nullable<int> PresentMinutes { get; set; }
    public Nullable<System.DateTime> PreviousExpiryDate { get; set; }
    public Nullable<System.DateTime> PresentExpiryDate { get; set; }
    public Nullable<int> PreviousAdminId { get; set; }
    public Nullable<int> PresentAdminId { get; set; }
    public string TriggerType { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
}

public partial class UserPriceMaster
{
    public int Slno { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<byte> FeatureID { get; set; }
    public Nullable<byte> CountryID { get; set; }
    public Nullable<int> PulseID { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
}

public partial class UserSubAccount
{
    public int id { get; set; }
    public string MobileNumber { get; set; }
    public string EMail { get; set; }
    public System.DateTime CreatedAt { get; set; }
    public System.DateTime UpdatedAt { get; set; }
    public string Name { get; set; }
    public string ResetPwdToken { get; set; }
    public Nullable<System.DateTime> ResetPwdTokenExpiredAt { get; set; }
    public Nullable<System.DateTime> ResetPwdSentAt { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
    public string PasswordHash { get; set; }
    public string MainUser { get; set; }
    public string MainUserMobileNumber { get; set; }
    public string ConferenceIds { get; set; }
    public Nullable<byte> IsActive { get; set; }
    public Nullable<long> MainAcUserId { get; set; }
    public string work_number { get; set; }
    public string last_name { get; set; }
    public string company { get; set; }
    public string website_url { get; set; }
    public string profile_pic { get; set; }
    public byte[] user_image { get; set; }
    public Nullable<int> imgstat { get; set; }
    public string devicetoken { get; set; }
    public string appsource { get; set; }
    public string deviceuniqueid { get; set; }
    public string androiddevicetoken { get; set; }
}

public partial class UserToken
{
    public int TokenId { get; set; }
    public Nullable<int> UserId { get; set; }
    public string Username { get; set; }
    public string Mobile { get; set; }
    public string TokenType { get; set; }
    public Nullable<byte> IsVerified { get; set; }
    public Nullable<System.DateTime> Created_at { get; set; }
    public string token { get; set; }
    public string Description { get; set; }
}

public partial class UserUnauthorizedAction
{
    public int ID { get; set; }
    public Nullable<int> UserId { get; set; }
    public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
}

public partial class xl_upload_logs
{
    public int id { get; set; }
    public Nullable<int> user_id { get; set; }
    public string file_path { get; set; }
    public string type { get; set; }
}

public partial class yconference_email_list
{
    public int slno { get; set; }
    public string token { get; set; }
    public string name { get; set; }
    public string email_id { get; set; }
    public Nullable<byte> is_opened { get; set; }
    public Nullable<byte> response { get; set; }
    public Nullable<System.DateTime> updatedTimeStamp { get; set; }
}

public partial class yconference_Emails_list
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
}

public partial class yconference_mails_list
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
}
