//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Optin
    {
        public int Slno { get; set; }
        public string UserNumber { get; set; }
        public string OptinNumber { get; set; }
        public string OptOutNumber { get; set; }
        public Nullable<bool> IsOptedIn { get; set; }
        public Nullable<System.DateTime> OptedInTimeStamp { get; set; }
        public Nullable<System.DateTime> OptedOutTimeStamp { get; set; }
    }
}
