//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string from_number { get; set; }
        public string to_number { get; set; }
        public Nullable<int> conf_id { get; set; }
        public string member_id { get; set; }
        public string conf_room { get; set; }
        public string member_type { get; set; }
        public string member { get; set; }
        public string requestuuid { get; set; }
        public string calluuid { get; set; }
        public string conf_type { get; set; }
        public string recorded_file { get; set; }
        public string conf_uuid { get; set; }
        public string call_status { get; set; }
        public string record_status { get; set; }
        public Nullable<bool> mute { get; set; }
        public Nullable<bool> deaf { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> digits_press { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string end_reason { get; set; }
        public string plivoip { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string District { get; set; }
        public string Mandal { get; set; }
        public string BatchId { get; set; }
        public Nullable<System.DateTime> MemberJoinTime { get; set; }
        public Nullable<System.DateTime> MemberExitTime { get; set; }
        public Nullable<bool> IsInbound { get; set; }
        public Nullable<byte> IsRetry { get; set; }
        public Nullable<byte> IsAutodial { get; set; }
        public Nullable<int> SubScriptionType { get; set; }
        public Nullable<double> AmountUsed { get; set; }
        public Nullable<int> TimeZoneMins { get; set; }
        public string PlivoCallUUID { get; set; }
        public Nullable<int> gatewayid { get; set; }
        public Nullable<int> PulseID { get; set; }
        public Nullable<byte> IsInterConnect { get; set; }
        public Nullable<int> ReceivingGatewayId { get; set; }
        public string NodeIp { get; set; }
    }
}
