//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Queue
    {
        public int slno { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> User_Job_No { get; set; }
        public string Mobile_Number { get; set; }
        public string Message { get; set; }
        public string Sender_Id { get; set; }
        public string Message_Type { get; set; }
        public Nullable<System.DateTime> Job_Done_Time_Stamp { get; set; }
        public string Sms_Response { get; set; }
        public Nullable<int> Sms_Status { get; set; }
        public Nullable<int> Entery_No { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> status { get; set; }
    }
}
