//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Details_Conf
    {
        public int slno { get; set; }
        public Nullable<int> contact_id { get; set; }
        public string Mobile_Number { get; set; }
        public string Message { get; set; }
        public string Sender_Id { get; set; }
        public string Message_Type { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<int> Category { get; set; }
    }
}
