//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTP_Queue
    {
        public int Email_ID { get; set; }
        public string From_display { get; set; }
        public string From_Addr { get; set; }
        public string To_Addr { get; set; }
        public string CC_Addr { get; set; }
        public string BCC_Addr { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public byte Mail_Sent { get; set; }
        public Nullable<byte> priority { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Discription { get; set; }
        public string reply_to { get; set; }
        public Nullable<int> university_id { get; set; }
        public Nullable<long> entryNo { get; set; }
        public Nullable<long> User_Email_Job_No { get; set; }
        public Nullable<int> lang_type { get; set; }
        public string Attachments { get; set; }
    }
}
