//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_group_contactsBackup
    {
        public int id { get; set; }
        public Nullable<int> contactid { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> inserted_ts { get; set; }
        public Nullable<System.DateTime> updated_ts { get; set; }
    }
}
