//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBalanceMaster
    {
        public int Slno { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
        public Nullable<byte> SubscriptionType { get; set; }
    }
}
