//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_login_activities_mod_mem
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string login_ip { get; set; }
        public string login_status { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public Nullable<System.DateTime> logout_time { get; set; }
        public string browser_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> source_type { get; set; }
    }
}
