//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToken
    {
        public int TokenId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Username { get; set; }
        public string Mobile { get; set; }
        public string TokenType { get; set; }
        public Nullable<byte> IsVerified { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string token { get; set; }
        public string Description { get; set; }
    }
}
