//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContactsTraking
    {
        public int Slno { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ContactId { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string PreviousContactName { get; set; }
        public string PreviousContactMobile { get; set; }
        public string PreviousContactEmail { get; set; }
        public string PreviousGroupName { get; set; }
        public string CurrentContactName { get; set; }
        public string CurrentContactMobile { get; set; }
        public string CurrentContactEmail { get; set; }
        public string CurrentGroupName { get; set; }
        public string EditedUserMobile { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
        public string UserChanges { get; set; }
    }
}
