//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPriceInfoHistory
    {
        public decimal Slno { get; set; }
        public Nullable<decimal> PriceInfoSlno { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<byte> FeatureId { get; set; }
        public Nullable<bool> PreviousIsActive { get; set; }
        public Nullable<bool> PresentIsActive { get; set; }
        public Nullable<byte> PreviousPulseId { get; set; }
        public Nullable<byte> PresentPulseId { get; set; }
        public Nullable<int> PreviousConcurrency { get; set; }
        public Nullable<int> PresentConcurrency { get; set; }
        public Nullable<int> PreviousMinutes { get; set; }
        public Nullable<int> PresentMinutes { get; set; }
        public Nullable<System.DateTime> PreviousExpiryDate { get; set; }
        public Nullable<System.DateTime> PresentExpiryDate { get; set; }
        public Nullable<int> PreviousAdminId { get; set; }
        public Nullable<int> PresentAdminId { get; set; }
        public string TriggerType { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
    }
}
