//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBalanceDepositHistory
    {
        public decimal Slno { get; set; }
        public Nullable<decimal> UserBalanceInfoSlno { get; set; }
        public Nullable<decimal> UserId { get; set; }
        public Nullable<double> BalanceBefore { get; set; }
        public Nullable<double> BalanceAfter { get; set; }
        public Nullable<bool> IsActiveBefore { get; set; }
        public Nullable<bool> IsActiveAfter { get; set; }
        public Nullable<System.DateTime> ExpiryDateBefore { get; set; }
        public Nullable<System.DateTime> ExpiryDateAfter { get; set; }
        public Nullable<decimal> AdminId { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
        public Nullable<int> SubscriptionTypePrevious { get; set; }
        public Nullable<int> SubscriptionTypePresent { get; set; }
        public Nullable<long> DialInMinutesPrevious { get; set; }
        public Nullable<long> DialInMinutesPresent { get; set; }
        public Nullable<long> DialOutMinutesPrevious { get; set; }
        public Nullable<long> DialOutMinutesPresent { get; set; }
    }
}
