//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMissedCallToGetInformation
    {
        public int Id { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> InsertedTimeStamp { get; set; }
        public Nullable<byte> IsCallBack { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
    }
}
