//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubAccount
    {
        public int id { get; set; }
        public string MobileNumber { get; set; }
        public string EMail { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string Name { get; set; }
        public string ResetPwdToken { get; set; }
        public Nullable<System.DateTime> ResetPwdTokenExpiredAt { get; set; }
        public Nullable<System.DateTime> ResetPwdSentAt { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string PasswordHash { get; set; }
        public string MainUser { get; set; }
        public string MainUserMobileNumber { get; set; }
        public string ConferenceIds { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<long> MainAcUserId { get; set; }
        public string work_number { get; set; }
        public string last_name { get; set; }
        public string company { get; set; }
        public string website_url { get; set; }
        public string profile_pic { get; set; }
        public byte[] user_image { get; set; }
        public Nullable<int> imgstat { get; set; }
        public string devicetoken { get; set; }
        public string appsource { get; set; }
        public string deviceuniqueid { get; set; }
        public string androiddevicetoken { get; set; }
    }
}
