//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class xl_upload_logs
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string file_path { get; set; }
        public string type { get; set; }
    }
}
