//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GT.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class yconference_email_list
    {
        public int slno { get; set; }
        public string token { get; set; }
        public string name { get; set; }
        public string email_id { get; set; }
        public Nullable<byte> is_opened { get; set; }
        public Nullable<byte> response { get; set; }
        public Nullable<System.DateTime> updatedTimeStamp { get; set; }
    }
}
